/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_WORD_FORMAT_TEST_PB_H_INCLUDED
#define PB_WORD_FORMAT_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _stringmsg { 
    pb_callback_t value; 
} stringmsg;

typedef struct _oneword { 
    uint32_t value; 
} oneword;

typedef struct _twoword { 
    uint32_t value; 
} twoword;

typedef struct _threeword { 
    bool has_value;
    twoword value; 
} threeword;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define oneword_init_default                     {0}
#define twoword_init_default                     {0}
#define threeword_init_default                   {false, twoword_init_default}
#define stringmsg_init_default                   {{{NULL}, NULL}}
#define oneword_init_zero                        {0}
#define twoword_init_zero                        {0}
#define threeword_init_zero                      {false, twoword_init_zero}
#define stringmsg_init_zero                      {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define stringmsg_value_tag                      2
#define oneword_value_tag                        1
#define twoword_value_tag                        300
#define threeword_value_tag                      1000

/* Struct field encoding specification for nanopb */
#define oneword_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,             1)
#define oneword_CALLBACK NULL
#define oneword_DEFAULT NULL

#define twoword_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   value,           300)
#define twoword_CALLBACK NULL
#define twoword_DEFAULT NULL

#define threeword_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,           1000)
#define threeword_CALLBACK NULL
#define threeword_DEFAULT NULL
#define threeword_value_MSGTYPE twoword

#define stringmsg_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define stringmsg_CALLBACK pb_default_field_callback
#define stringmsg_DEFAULT NULL

extern const pb_msgdesc_t oneword_msg;
extern const pb_msgdesc_t twoword_msg;
extern const pb_msgdesc_t threeword_msg;
extern const pb_msgdesc_t stringmsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define oneword_fields &oneword_msg
#define twoword_fields &twoword_msg
#define threeword_fields &threeword_msg
#define stringmsg_fields &stringmsg_msg

/* Maximum encoded size of messages (where known) */
/* stringmsg_size depends on runtime parameters */
#define oneword_size                             6
#define threeword_size                           10
#define twoword_size                             7

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
