/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "word-format-test.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(oneword, oneword, AUTO)


PB_BIND(twoword, twoword, 2)


PB_BIND(threeword, threeword, 2)


PB_BIND(stringmsg, stringmsg, AUTO)



